spring.application.name=customer-api
spring.mvc.problemdetails.enabled=true
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/customer_db}
spring.datasource.username=${DB_USERNAME:customer_app}
spring.datasource.password=${DB_PASSWORD:customer_app}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false